name: Daily Telegram Reminder

on:
  schedule:
    - cron: '0 4 * * *'  # الساعة 7 صباحًا بتوقيت السعودية
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install requests
        run: python3 -m pip install requests

      - name: Run superlight.py
        run: python3 superlight.py
