name: Run Python Every Morning

on:
  schedule:
    - cron: '0 4 * * *'  # كل يوم الساعة 4 صباحًا UTC = 7 صباحًا السعودية
  workflow_dispatch:  # يتيح لك تشغيله يدويًا أيضًا

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: install requests
      - run: |
         python3 -m pip install requests

      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run the script
        run: python main.py
